language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - tip

# Waiting on https://github.com/travis-ci/apt-source-whitelist/pull/346 before this will work
# addons:
#   apt:
#     sources:
#       - google-cloud
#     packages:
#       - google-cloud-sdk

env:
  - ISSUER="http://localhost:8080" DATABASE_URL="datastore://hydra-gcp-test?namspace=hydra" SYSTEM_SECRET="notsosecretnotsosecretnotsosecret" CONSENT_URL="http://localhost:8080/consent" FORCE_ROOT_CLIENT_CREDENTIALS= "admin:password"

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/alecthomas/gometalinter

install:
  - $GOPATH/bin/gometalinter --install
  - curl https://sdk.cloud.google.com > install.sh && chmod +x install.sh
  - ./install.sh --disable-prompts
  - $HOME/google-cloud-sdk/bin/gcloud components install cloud-datastore-emulator --quiet
  - make get

before_script:
  - $HOME/google-cloud-sdk/bin/gcloud beta emulators datastore start &
  - $($HOME/google-cloud-sdk/bin/gcloud beta emulators datastore env-init)

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - make fmt vet build
