language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/alecthomas/gometalinter

install:
  - $HOME/gopath/bin/gometalinter --install
  - make get

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - make fmt vet build
